
name: Testes
# Gatilhos / Programados ou Acionados sempre que ocorrer algum evento
on:
  push:
    branches: [ main ]

jobs:
  build:

#  Qual máquina que o teste vai ser executado

    runs-on: ubuntu-latest
  # Passos
    steps:
    - uses: actions/checkout@v2
    
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        
    
    - run: npm install
    - run: npm run cy:run
      continue-on-error: true
    - run: npm run report:merge
    
    - run: npm run report:mocha
    
    # Github Pages - publicar relatório
    - name: Deploy to GitHub Pages
    # You may pin to the exact commit or the version.
   # uses: JamesIves/github-pages-deploy-action@6ce741f5d4e01e15f9ea5ec96df1a43f522c330f
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with: 
        GITHUB-TOKEN: ${{ secrets.GITHUB_TOKEN}}
        BRACH: gh-pages
        FOLDER: mochawesome-report
        
    
    
